- name: Configuration nginx
  hosts: nginx
  become: True
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: copie du fichier de conf nginx
      copy: src=/opt/nginx.conf dest=/etc/nginx/sites-available/default

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: copie de index.html
      template: src=/opt/index.html dest=/usr/share/nginx/html/index.html
        mode=0644

    - name: restart nginx
      service: name=nginx state=restarted
